---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: machinepool-for-clusterclaim-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - ref: machinepool-for-clusterclaim-trigger-binding
      template:
        ref: machinepool-for-clusterclaim-trigger-template