apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ssh-credentials-secret
spec:
  data:
    - secretKey: id_rsa
      remoteRef:
        key: 983ed7e6-c987-7131-bb10-fec80df1a0b6
    - secretKey: known_hosts
      remoteRef:
        key: ed83cc61-b789-fcde-4785-dc9ef96f198a
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: otp-repo-ssh-bot-creds
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        id_rsa: {{ .id_rsa }}
        known_hosts: {{ .known_hosts }}
        config: ""